### ISSUE TITLE
Loading data from drio just once

### ISSUE THREAD

**Issue by havard-skjerve-4ss** [4Subsea/drio-python#28]
Typical engineroom apps load daily data, which should match the drio 24h chunks well. However, when loading with code

`start, end = "2022-01-31 00:00", "2022-02-01 00:00"`
`ts = drio_client.get(ts_id, start, end)`

it seems to load 2 24-periods (01-31 and 02-02?), based on timings of load duration.   Subtracting 1ns cuts loading time to 50%. If caching, only  the 1st 24hrs are stored.

This may potentially cause massive increase in drio downloads.

[issue_example.zip](https://github.com/4Subsea/drio-python/files/7995750/issue_example.zip)

**Comment by heidi-holm-4ss** [comment]
https://4insight.atlassian.net/browse/DST-253
